## NumPy

## 1. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [81]:
import numpy as np

In [82]:
array1 = np.random.randint(100,200, size= (5,2))

In [83]:
print(array1)

[[154 139]
 [130 115]
 [156 199]
 [192 172]
 [125 102]]


## 2. Write a NumPy program to create a 3x3x3 array filled with arbitrary values and find the minimum and maximum values.

In [79]:
ran_arr = np.random.random((3,3,3))

In [80]:
print(ran_arr)

[[[5.15601232e-01 2.44761372e-01 7.98104097e-01]
  [4.47155328e-01 6.15123197e-01 9.56050684e-01]
  [5.39367775e-01 5.69623279e-01 5.77478402e-01]]

 [[2.74738912e-01 9.94577124e-03 7.19074758e-01]
  [8.35631003e-01 3.21155073e-02 3.52631066e-04]
  [7.04749959e-02 4.14168167e-01 9.96016242e-01]]

 [[5.66292395e-01 7.26425444e-01 9.56635903e-01]
  [8.48673102e-01 6.27701719e-01 1.13596516e-01]
  [2.37864227e-01 3.04775984e-01 6.71977304e-01]]]


In [6]:
ran_arr.max()

0.9734966376266271

In [7]:
ran_arr.min()

0.003555070858975773

## 3. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [77]:
dia_Arr = np.diag([1,2,3,4,5])

In [78]:
print(dia_Arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


## 4. . Given an array
 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ])
    - i) Extract all odd numbers from arr
    - ii) Replace all odd numbers in arr with -1

In [71]:
 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ])

In [72]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [73]:
odd = []
for x in arr:
    if x%2!=0:       
        odd.append(arr[x])
        arr[x]= -1
      

In [74]:
# odd list 
odd

[1, 3, 5, 7, 9]

In [75]:
# updated array
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 5. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.

In [15]:
dia_Arr = np.diag([1,1,1])

In [67]:
print(dia_Arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 6. Write a NumPy program to convert an array to a float type.

In [17]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [18]:
x = np.asfarray(a)

In [66]:
print(x)

[[34 73]
 [82 12]
 [53 66]]


## 7. Write a NumPy program to generate five random numbers from the normal distribution.

In [20]:
x = np.random.normal(size = 5)

In [65]:
print(x)

[[34 73]
 [82 12]
 [53 66]]


## 8. Following is the input NumPy array delete column two and insert following new column in its place.
    -sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,66]])
    -newColumn = numpy.array([[10,10,10]])

In [22]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

In [23]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [24]:
x = np.delete(sampleArray,1,1)

In [25]:
x

array([[34, 73],
       [82, 12],
       [53, 66]])

In [26]:
newArr = np.insert(x,1,newColumn,1)

In [64]:
print(newArr)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


## 9. Write a NumPy program to compute the multiplication of two given matrices.

In [28]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
b = np.array([10,11,12])
b

array([10, 11, 12])

In [30]:
print(np.multiply(a,b))

[[ 0 11 24]
 [30 44 60]
 [60 77 96]]


## 10. Write a NumPy program to create a random vector of size 10 and sort it.

In [31]:
np_rand = np.random.randn(1,10)

In [32]:
np_rand

array([[-0.74682886,  0.05168828, -0.22972414, -0.40454567,  0.69346916,
         0.78225148, -1.33210037,  1.84152634, -1.24643894,  0.18863346]])

In [34]:
np_rand.sort()

In [63]:
# sorted vector
print(np_rand)

[[-1.33210037 -1.24643894 -0.74682886 -0.40454567 -0.22972414  0.05168828
   0.18863346  0.69346916  0.78225148  1.84152634]]


## 11. Write a NumPy program to compute the covariance matrix of two arrays.

In [43]:
a1 = np.random.randn(1,10)
a2 = np.random.randn(1,10)

In [44]:
a1

array([[ 1.24458968,  0.46849356, -0.35646775, -0.15474942,  0.2844827 ,
         1.53800276, -1.41735226, -0.90174397,  0.37752035, -0.29825622]])

In [45]:
a2

array([[-0.6941964 , -0.66385593,  0.16198253, -0.18974812,  2.7513013 ,
        -2.26936532,  1.53231608,  0.05681093,  0.98164451, -0.16074512]])

In [62]:
print(np.cov(a1,a2))

[[ 0.81753891 -0.64818434]
 [-0.64818434  1.86870797]]


## 12. Create a 4X2 integer array and Prints its :
     - i)The shape of an array.
     - ii) Array dimensions.
     - iii) The Length of each element of the array in bytes

In [49]:
array1 = np.random.randint(100,200, size= (4,2))

In [61]:
print(array1)

[[168 146]
 [140 125]
 [111 159]
 [109 196]]


In [51]:
array1.shape

(4, 2)

In [52]:
array1.ndim

2

In [54]:
array1.itemsize

4

In [56]:
array1.nbytes

32

## 13. Write a NumPy program to concatenate element-wise two arrays of string

In [60]:
s1 = np.array(['mango','apple'])
s2 = np.array(['sour','sweet'])

s3 = np.char.add(s1,s2)
print(s3)

['mangosour' 'applesweet']



## 14. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [96]:
sarray = np.array(['i am going to home'])
print(sarray)

# capitalize array
print('Capitalize - ', np.char.capitalize(sarray))
print('Lower - ', np.char.lower(sarray))
print('Uppercase - ', np.char.upper(sarray))
print('Swapcase - ', np.char.swapcase(sarray))
print('Title - ', np.char.title(sarray))


['i am going to home']
Capitalize -  ['I am going to home']
Lower -  ['i am going to home']
Uppercase -  ['I AM GOING TO HOME']
Swapcase -  ['I AM GOING TO HOME']
Title -  ['I Am Going To Home']


## 15. Write a NumPy program to convert a given array into a list.

In [132]:
sarr = np.array([[2,3,4,5],[9,8,9,6]])
sarr

array([[2, 3, 4, 5],
       [9, 8, 9, 6]])

In [133]:
#slist = list(sarr)
#slist
print(sarr.tolist())
type(sarr.tolist())

[[2, 3, 4, 5], [9, 8, 9, 6]]


list

## 16. Write a NumPy program to compute the sum of all elements, sum of each column and sum of each row of a given array.

In [110]:
narr = np.array([[2,4],[5,7]])
print('The array\n', narr)

The array
 [[2 4]
 [5 7]]


In [115]:
# sum of col
sumcol = np.sum(narr,axis= 0)
print('Sum of col\n',sumcol)

Sum of col
 [ 7 11]


In [117]:
# sum of row
sumrow = np.sum(narr, axis = 1)
print('Sum of Row\n',sumrow)

Sum of Row
 [ 6 12]


## 17. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [119]:
arr1 = np.random.randint(100,200, size= (10,4))
print('The Array \n',arr1)

The Array 
 [[141 181 186 139]
 [181 176 178 116]
 [174 183 141 123]
 [147 138 198 171]
 [111 192 182 119]
 [199 115 136 187]
 [100 138 158 109]
 [190 181 159 193]
 [180 163 157 147]
 [163 182 175 150]]


In [121]:
arr2 = arr1[:5,:]
print('First 5 rows of arr1\n',arr2)

First 5 rows of arr1
 [[141 181 186 139]
 [181 176 178 116]
 [174 183 141 123]
 [147 138 198 171]
 [111 192 182 119]]


## 18. Write a NumPy program to get the unique elements of a 1D and 2D array.

In [151]:
a1 = np.array([2,3,4,3,4,5,6])
print('The Array\n',a1)

The Array
 [2 3 4 3 4 5 6]


In [152]:
print('unique value in 1D array\n',np.unique(a1))


unique value in 1D array
 [2 3 4 5 6]


In [153]:
a3 = np.array([[2,3],[3,4]])
a3

array([[2, 3],
       [3, 4]])

In [154]:
print('unique value in 2D array\n',np.unique(a3))

unique value in 2D array
 [2 3 4]


## 19. Write a NumPy program to get the unique elements of an array. 
    - arr= [ -10 12.12 -0.2]


In [161]:
arr= [ -10, 12.12, -0.2]
arr

[-10, 12.12, -0.2]

In [162]:
print('The unique elements are - ',np.unique(arr))

The unique elements are -  [-10.    -0.2   12.12]


## 20. Write a NumPy program to save a given array to a text file and load it. You have to save and load files using numpy library

In [163]:
a3 = np.array([[2,3],[3,4]])
a3

array([[2, 3],
       [3, 4]])

In [166]:
np.savetxt("array.txt",a3)

In [194]:
file = open('array.txt')

In [195]:
# reading back from text file
print(file.readline())
print(file.readline())



2.000000000000000000e+00 3.000000000000000000e+00

3.000000000000000000e+00 4.000000000000000000e+00

